### ISSUE TITLE
Refactoring request: move function MODBUS_CRC to a separate LIB

### ISSUE THREAD

**Issue by titobrasolin** [digidotcom/DCRabbit_10#12]
Function `MODBUS_CRC` is defined both in `modbus_master.lib` and `modbus_slave.lib`:

- https://github.com/digidotcom/DCRabbit_10/blob/master/Lib/Rabbit4000/Modbus/modbus_master.lib#L626
- https://github.com/digidotcom/DCRabbit_10/blob/master/Lib/Rabbit4000/Modbus/modbus_slave.lib#L741

Moving it to a separate library file would allow to `#use modbus_master.lib` and `modbus_slave.lib` in the same project. The two libraries are currently mutually exclusive (`ERROR [...]  : Duplicate MODBUS_CRC found [...]`)

I'm working on a device that should be configurable as master or slave at runtime, that's why such a change would be useful to me.

**Comment by tomlogic** [comment]
Would it be better to remove that function entirely and just make use of crc16_calc() with a starting value of `0xFFFF` (similar to how `Modbus_Slave_BL4S1xx.lib` calls `getcrc()`)?  I see that Digi doesn't provide sample programs for Modbus -- is the existing CRC calculation correct?

I just did a short test and `MODBUS_CRC()` gave a different answer than what was shown on [this webpage](https://www.lammertbies.nl/comm/info/crc-calculation.html), but my `crc16_calc()` routine had the correct answer.

**Comment by titobrasolin** [comment]
Good point Tom. I did some research (I'm not an expert, just maintaining some legacy code) and found that the standard CRC for Modbus is CRC-16-ANSI also known as CRC-16-IBM, normal hexadecimal algebraic polynomial being 8005: https://en.wikipedia.org/wiki/Modbus#Frame_format

The `crc16_calc()` function, on the other hand, returns CRC-16-CCITT, polynomial 0x1021.

More info: https://en.wikipedia.org/wiki/Polynomial_representations_of_cyclic_redundancy_checks

In fact my code _does_ `#define USE_MODBUS_CRC`.
My guess is that `MODBUS_CRC()` is definitely needed for standard Modbus operations.

**Comment by titobrasolin** [comment]
By the way, maybe moving `MODBUS_CRC()` into `Lib/Rabbit4000/Math/crc16.lib` makes sense.

**Comment by tomlogic** [comment]
Moved MODBUS_CRC() to CRC16.LIB in commit 0d0f237f74.
