### ISSUE TITLE
Function _n_strcpy (libc/string.c) not returning the expected value

### ISSUE THREAD

**Issue by titobrasolin** [digidotcom/DCRabbit_10#13]
According to the manual `_n_strcpy(char * dst, ...);` should return a pointer to "dst".
Example:
```c
far char dst2[10];
void main(void) {
   char dst[10];

   char *c = _n_strcpy(dst, "SOMETHING");
   far char *c2 = _f_strcpy(dst2, "SOMETHING");

   printf("dst=%p, c=%p\n", dst, c);
   printf("dst2=%Fp, c2=%Fp\n", dst2, c2);
}
```
But the output is not exactly as expected:

    dst=DFF2, c=DFE8
    dst2=107FF6, c2=107FF6

It looks like the output of _n_strcpy is `dst` minus the number of copied bytes.

**Comment by titobrasolin** [comment]
In my opinion the problem is here: https://github.com/digidotcom/DCRabbit_10/blob/10.72B/Lib/Rabbit4000/libc/string.c#L215

LDI: Loads the memory location whose address is DE with the data at the address in HL. **Then the value in BC is decremented** and the value in DE and HL is incremented.

**Comment by tomlogic** [comment]
Thanks for the detailed bug report, @titobrasolin!  Hope this one didn't cause you too many headaches.  Pushing a patch out now.
