### ISSUE TITLE
RabbitWeb DC10.70 losing precision on small values

### ISSUE THREAD

**Issue by tomlogic** [digidotcom/DCRabbit_10#2]
This was an issue reported by "Phil" on the rabbit-semi Yahoo group in December 2013.  [His original message](https://groups.yahoo.com/neo/groups/rabbit-semi/conversations/messages/42000) might only be visible to members of that group.

> I've just discovered that RabbitWeb seems to be having issues displaying small values correctly on my web forms.  All these comment apply to FLOAT type values.
> BTW, this isn't a precision problem, it's a display problem.
> eg: if I enter a float number on a form, and then have RabbitWeb display it, I have verified that the number is STORED correctly, but just not displayed back correctly...  
> Here are some examples of what is entered, vs what is displayed
> Entered   Displayed
> 1.0202     1.0202      GOOD
> 1.0002     1.0002      GOOD
> 0.0202     0.020       BAD
> 0.02         0.0           Really BAD
> 0.099       0.09         BAD
> 0.09         0.0           Really Bad
> This only seems to happen with numbers samller than 0.1
> Any suggestion onnhow to fix this

**Comment by DrASK** [comment]
FYI: I can see the original message.
