### ISSUE TITLE
Wrong formatting of extra headers in function _httpc_req

### ISSUE THREAD

**Issue by titobrasolin** [digidotcom/DCRabbit_10#20]
https://github.com/digidotcom/DCRabbit_10/blob/7f990cd005e4ad9f8aa4f4fe337a96eca8effda3/Lib/Rabbit4000/tcpip/http_client.lib#L2136

`s->extra_headers` is a **far** pointer, in my opinion it should be printed like this:
```
snprintf(&buffer[bytes], sizeof(buffer) - bytes, "%Fs", s->extra_headers);
```
or maybe like this:
```
snprintf(&buffer[bytes], sizeof(buffer) - bytes, "%" PRIsFAR, s->extra_headers);
```
I noticed the problem because I tried to pass some xdata to the `httpc_set_extra_headers` function and it did not work (headers were dirtied with random characters).

**Comment by DrASK** [comment]
I completely agree. And very much supportive of the second example.

**Comment by tomlogic** [comment]
Fixed using `"%ls"` which is far more common than `"%Fs"` (appearing 413 vs. 2) in the Dynamic C libraries (although both will work).

`PRIsFAR` is only defined in `include/xbee/platform_rabbit.h` and isn't in any of the standard Rabbit headers.
