### ISSUE TITLE
errors even in very simple floating point calculations

### ISSUE THREAD

**Issue by titobrasolin** [digidotcom/DCRabbit_10#21]
Here is an example:
```c
int main()
{
  long a = 225L;
  float b = a / (float)a; // <- should be 1.0
  float c = b * a; // <- should be 1.0 * 225 = 225.0
  long d = (long)c; // <- should be 225

  printf("a = %ld\n", a);
  printf("b = %f\n",  b);
  printf("c = %f\n",  c);
  printf("d = %ld\n", d);

   while (!kbhit());
}
```
And the output is:

    a = 225
    b = 1.000000
    c = 224.999984
    d = 224

floats are not supposed to be completely accurate, but I didn't expect an error in such a simple calculation.

Here is the "real world" example where I noticed the issue:
```c
#define TIMEZONE ( gmtoff / 3600.0 )
long gmtoff = 3600L;

int main()
{
  long seconds;
  int rc = rtc_timezone( &seconds, NULL);

  printf("seconds = %ld\n", seconds);

  while (!kbhit());
}
```
The output is:

    seconds = 3599

**Comment by tomlogic** [comment]
You are correct, the Rabbit's floating point is often less accurate than other platforms with a 32-bit `float`.  I believe this is a legacy of floating point code originally written for the limited features of the Rabbit 2000 and Rabbit 3000 processors, where there was a tradeoff for speed in favor of accuracy.  As far as I can tell, no one revisited the assembly code used for `F_mul` and `F_div` and updated them to take advantage of 32-bit `JKHL` and `BCDE` registers (not to mention `PW`, `PX`, `PY` and `PZ`).

The division operation `X / Y` starts by calculating `1 / Y` and likely loses some precision there.  It then does a floating-point multiply with `X` and could lose precision there as well.

My recommendation is that if you're going to convert from `float` back to `long`, you add `0.5` before the typecast.

For improved floating point precision, it might be possible to port portions of [Berkeley SoftFloat](http://www.jhauser.us/arithmetic/SoftFloat.html) Release 2c to replace `F_mul` and `F_div` (and potentially other core functions).  But without a large test suite, it would be risky to rewrite the floating point code using Rabbit 4000 opcodes.
