### ISSUE TITLE
DLP/DLM for RCM6000 family

### ISSUE THREAD

**Issue by wcoto** [digidotcom/DCRabbit_10#22]
Is there a sample/tutorial in Dynamic C 10.72D for implementing a project by using the DLP/DLM model?

**Comment by tomlogic** [comment]
With Dynamic C 10, we recommend using RemoteProgramUpdate for RCM6000 hardware.  That feature allows for power fail safe updates by having two firmware images stored on the serial boot flash.  The first 1KB (IIRC) of the BIOS chooses which image to boot from.

Take a look at `Samples/RemoteProgramUpdate` for various methods of loading new firmware (TFTP, HTTP client/server, and SD card).

In addition, [App Note 421](http://ftp1.digi.com/support/documentation/022-0144_C.pdf) describes the feature in more detail.
