### ISSUE TITLE
Possible minor bug in Samples/RemoteProgramUpdate/pages/upload.zhtml

### ISSUE THREAD

**Issue by titobrasolin** [digidotcom/DCRabbit_10#23]
https://github.com/digidotcom/DCRabbit_10/blob/58675d7e8ee9db68b7e2124f7f14ed9f393c34d3/Samples/RemoteProgramUpdate/pages/upload.zhtml#L21

Perhaps it should be `$firmware.error` because there is no field named `install_error` in struct `firmware`:

https://github.com/digidotcom/DCRabbit_10/blob/58675d7e8ee9db68b7e2124f7f14ed9f393c34d3/Samples/RemoteProgramUpdate/upload_firmware.c#L212

**Comment by tomlogic** [comment]
Thanks @titobrasolin!  Sorry for letting this fall through the cracks.
