### ISSUE TITLE
How is snprintf supposed to work in function _web_printf, case _DK_TSTRING?

### ISSUE THREAD

**Issue by titobrasolin-ke** [digidotcom/DCRabbit_10#26]
https://github.com/digidotcom/DCRabbit_10/blob/5d226fe0eadb90fd9991bbf413ff57082571c5ad/Lib/Rabbit4000/RabbitWeb/RWEB_GENERIC.LIB#L1542

According to the comments:

   	// String binary length is passed as extra parameter, which allows formats
   	// like %.*s to be used for force the resulting field width to be
   	// constant regardless of the string length.

This is not how `snprintf` works in my tests, for instance:

```c
int main()
{
  char dest[100];
  snprintf( dest, sizeof(dest), "%.*s", 4, "SOMETHING");
  printf(dest); // Output: "SOME", as expected.
}
```

The precision (4) must be supplied _before_ the string ("SOMETHING").
If I pass it as an extra parameter (i.e. after the string to print) the output is not as expected.

**Comment by neacsum** [comment]
You are correct and that is a bug in RWEB module. The [C standard](http://www.cplusplus.com/reference/cstdio/printf/) also says the precision argument should be passed **before** the argument to be converted. Also, if you look at the do_prnt function ([stdio.lib lines 547 and after](https://github.com/digidotcom/DCRabbit_10/blob/5d226fe0eadb90fd9991bbf413ff57082571c5ad/Lib/Rabbit4000/STDIO.LIB#L544)), you see that precision argument is extracted from va_arg list before the the argument to be converted.

**Comment by tomlogic** [comment]
Good eye.  I agree that it's a bug, but do you have a zhtml page that demonstrates the failure?

If you open a PR for the fix, I can merge it.  Otherwise I'll make the change myself sometime this week.

**Comment by titobrasolin-ke** [comment]
> I agree that it's a bug, but do you have a zhtml page that demonstrates the failure?

@tomlogic this sample is a good starting point:

    Samples/tcpip/rabbitweb/web.c
    Samples/tcpip/rabbitweb/pages/web.zhtml

The `echo($my_string)` in `web.zhtml` (line 31) has the same effect as `printf("%s", $my_string)`.

`printf("%Fs (%d)", $my_string)` prints out "Hello, world! (21)", but `printf("%.*s", $my_string)` just doesn't work: in my tests it produces an empty string, but I guess in general the results can be quite random.

> If you open a PR for the fix, I can merge it

Unfortunately I couldn't come up with an easy fix...
In the short term, at least I would delete that somewhat misleading comment

**Comment by tomlogic** [comment]
OK, I think I understand the problem better now.  Right now, the current code is expected to work for `%s` and `%.*s`, but it's impossible to craft an `snprintf()` call that will work for that.

My current thought is that the code will need to see if `spec` contains a `'*'` character, and use a different `snprintf()` call in that case.  But that runs the risk of breaking existing code with that character outside of the actual format (e.g., `"* %Fs"`).

**Comment by tomlogic** [comment]
@titobrasolin-ke, is this a feature that you need, or is it something where I should correct the documentation and take out the additional `snprintf()` parameter of the string's maximum length?

**Comment by titobrasolin-ke** [comment]
@tomlogic, I don't really need the `"%.*s"` feature, I just noticed something "strange" in the code.
Besides, the official documentation does not mention it: http://ftp1.digi.com/support/documentation/0200057_d.pdf

I think you shouldn't waste time on non-trivial implementation of an undocumented feature, just correct the comments and leave the code as it is: as far as we know that extra `web_size(wc)` parameter never did any harm and who knows? Maybe some developer is taking advantage of it in some way...

@tomlogic Thank you so much for your thoughtful and constant support
